config/routes.rb
Rails.application.routes.draw do
  post 'spots/:id/edit' => 'spots#edit'
  delete 'spot/:id' => 'spots#destroy'
  devise_for :users, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
  resources :charges
  get 'dashboard/index' => 'dashboard#index'
  post 'notifications/notify_host'
  root 'home#index'
  post 'spots/new' => 'spots#create'
  resources :dashboard
  get 'dashboard/:id/show' => 'dashboard#show'
  resources :bookings
  resources :users, only: [:show]
  resources :spots do
    resources :availabilities
    member do
      get 'street'
      get 'city'
      get 'zip'
      get 'listing'
      get 'pricing'
      get 'description'
      get 'photo_upload'
    end
  end
  get 'book_it' => "bookings#create"  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  has_many :spots
  has_many :bookings
  has_many :availabilities
  devise :omniauthable

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable


end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  require 'google_maps_service'

  def index
    @dashboard = current_user
    @spots = current_user.spots
    @bookings = current_user.bookings
    @availabilities = Availability.all
    @availability = Availability.new

    GoogleMapsService.configure do |config|
      config.key = ENV['MAPS']
      config.retry_timeout = 20
      config.queries_per_second = 10
      gmaps = GoogleMapsService::Client.new

      # query = [Spot.find(1).street, Spot.find(1).city, "FL"].join(', ')
      #Grabs first 2 spots. Eventually grab all spots and translating
      spots = current_user.spots

      #map over all spots
      gon.latlng = spots.map do |spot|
        #creates query for gmaps
        query = [spot.street, spot.city, "FL"].join(', ')
        #translates to latitude/long
        results = gmaps.geocode(query)
        #parse data

        # Requires real addresses for host locations
        results[0][:geometry][:location].values
        end

      end

      @spot = Spot.new

  end

  def show
    @spot = Spot.find(params[:id])
    gon.current_street = @spot.street
    GoogleMapsService.configure do |config|
      config.key = ENV['MAPS']
      config.retry_timeout = 20
      config.queries_per_second = 10
    gmaps = GoogleMapsService::Client.new
    @routes = gmaps.directions(
    '549 nw 28th st, Miami, FL, 33127, USA',
    '79 sw 12th st, Miami, FL, 33130, USA',
    mode: 'driving',
    alternatives: false)
    gon.start_address = @routes[0][:legs][0][:start_address]
    gon.end_address = @routes[0][:legs][0][:end_address]
    gon.center_lat = @routes[0][:legs][0][:start_location][:lat]
    gon.center_lng = @routes[0][:legs][0][:start_location][:lng]


  end

  end


  private


end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/views/dashboard/_hosting_card.html.erb
<% current_user.spots.each_with_index do |spot, i| %>
  <div class="card">
    <div class="card-content">
      <h5><%= spot.street %></h5>
      <p><%= spot.city %></p>
      <p><%= spot.zip %></p>
      <p>$<%= spot.price %>.00/hr</p>
      <p><%= spot.description %></p>
      <p>Availabilities:</p>
      <% spot.availabilities.each do |x| %>
        <p><%= x.to.strftime("%I:%M %p") %> - <%= x.from.strftime("%I:%M %p") %></p>
      <% end %>
    </div>
    <div class="card-action" id="hosting-spots-card">
      <ul id="hosted-spot-buttons">
        <a class="modal-trigger" href="#modal_<%= dom_id(spot) %>", id="dashboard-hosting-button"><i class="small material-icons">timer</i>Availability</a>

        <p><%= link_to edit_spot_path(spot), :method => :update, class: "", id:"dashboard-hosting-button" do %>
          Edit Spot<i class="small material-icons">edit</i>
        <% end %></p>
        <p><%= link_to spot_path(spot), :method => :delete, class: "", id:"dashboard-delete-button" do %>
          Remove<i class="small material-icons">delete</i>
        <% end %></p>
        <!-- Modal for updating spot availability -->
        <div id="modal_<%= dom_id(spot) %>" class="modal">
          <div class="modal-content">
            <%= render 'availabilities/form', :spot => spot, :availability => @availability %>
          </div>
        </div>
      </ul>

    </div>
  </div>
<% end %>

app/views/dashboard/_left_sidebar.html.erb
<div class="col s3" id="dashboard-sidebar">

    <div class="dashboard-welcome">
      <div class="dashboard-welcome-content">
        <h5>Welcome, <%= current_user.name %>!</h5>
        <p><%= current_user.email %></p>
        <p><%= current_user.phone_number %></p>
      </div>
    </div>
    <div class="dash-sidebar-links">
      <a href="/spots", class="waves-effect btn #ef6c00 orange darken-3", id="become-host-button"><i class="small material-icons">directions_car</i>Park Now</a>
      <a class="waves-effect btn #42a5f5 blue lighten-1 modal-trigger" href="#modal1", id="become-host-button"><i class="small material-icons">add_location</i>Become A Host</a>
      <div class="dash-sublinks-container">
      <i class="small material-icons">bookmark</i><li><a class="dash-sublinks" href="/bookings">Bookings</a></li>
      <i class="small material-icons">monetization_on</i><li><a class="dash-sublinks" href="#">Earnings</a></li>
      <i class="small material-icons">thumb_up</i><li><a class="dash-sublinks" href="#">Refer A Friend</a></li>
      <i class="small material-icons">local_phone</i><li><a class="dash-sublinks" href="#">Support</a></li>
      <i class="small material-icons">edit</i><li><a class="dash-sublinks" href="#">Edit your profile</a></li>
      </div>
    </div>
</div>

app/views/dashboard/_reservation_card.html.erb
<% current_user.bookings.each do |booking| %>
  <div class="card">
    <div class="card-content">
      <h5>Current Parking</h5>
      <% if booking.availability.spot.nil? %>
      <p>You dont have any bookings</p>
      <% else %>
        <p><%= booking.availability.spot.street%></p>
        <p><%= booking.availability.spot.description%></p>
          <p>Parking Valid Until: </p><%= booking.availability.from.strftime("%I:%M %p") %>
        </p><%= booking.availability.from.strftime("%m/%d/%Y")%></p>
        <% end  %>
    </div>
    <div class="card-action">
      <%if booking.availability.spot != nil %>
      <p><%= link_to dashboard_path(booking.availability.spot), class: "", id:"dashboard-hosting-button" do %>
        Get Directions<i class="small material-icons">directions</i>
      <% end %></p>
      <% end %>
      <% if booking.time_remaining %>
        <i class="small material-icons">av_timer</i><p>You have <%= booking.time_remaining %> left on your parking reservation!</p>
      <% else %>
        <i class="small material-icons">av_timer</i><p>Your parking reservation has expired!</p>
      <% end %>
      <p><%= link_to booking,  method: :delete, id:"dashboard-hosting-button", data: { confirm: 'Are you sure you want to cancel?' } do %>
        Cancel Parking<i class="small material-icons">cancel</i>
      <% end %></p>
      <p> <%= link_to "On your way?", notifications_notify_host_path, method: :post %> </p>
    </div>
  <% end %>
  </div>

app/views/dashboard/_right_sidebar.html.erb
<!-- Right Sidebar Content? -->
<div class="col s3">
  <!-- Stripe connect card -->
  <div class="card small">
    <div class="card-image">
      <div id="refer-a-friend">
        <%=link_to image_tag("stripe.png"), user_stripe_connect_omniauth_authorize_path %>
      </div>
    </div>
    <!-- Stripe connect card Content -->
    <div class="refer-a-friend">
      <h5>Connect with Stripe</h5>
      <p>Get authenticated through stripe in minutes, and you'll have access to thousands of
      spots around your city!</p>
    </div>
  </div>

  <!-- Refer a friend -->
  <div class="card small">
    <div class="card-image">
      <div id="refer-a-friend">
        <%= image_tag("referAFriend.jpg") %>
      </div>
    </div>
    <!-- Refer a friend Content -->
    <div class="refer-a-friend">
      <h5>Refer A Friend</h5>
      <p>Earn extra cash by becoming a host and referring a friend to do the same!</p>
    </div>
  </div>
</div>

app/views/dashboard/_searchbar.html.erb
<div class="dash-search-bar">
  <h5>Search Parking Near You</h5>
  <%= form_tag(spots_path, method: :get) do %>
  <%= text_field_tag :zip, nil, placeholder: "Search Zip Codes", :maxlength => 5 %>
  <%= submit_tag 'Search', class: "btn #42a5f5 blue lighten-1", id: "search-button" %>
  <% end %>
</div>

app/views/dashboard/index.html.erb
<div class="dashbackground">

  <!-- Modal for creating new hosting spot -->
  <div id="modal1" class="modal">
    <div class="modal-content">
      <%= render 'spots/form' %>
    </div>
  </div>


  <div class="row">
    <!-- DESKTOP VIEW (Sidebar) -->
    <div class="hide-on-small-only">
      <div class="row">
        <!-- Sidebar panel -->
        <%= render 'left_sidebar' %>

        <!-- Page content  -->
        <div class="col s6">

          <!-- Dashboard main content -->
          <div class="" id="dash-container">
            <div class="row">
              <div class="col s12">
                <!-- Dashboard Search Bar -->
                <%= render 'searchbar' %>

                <div id="mapDash"></div>

                <!-- Reserved Spots Column -->
                <%if current_user.bookings.empty? %>
                  <div class="col s6" id="reserved-spots">
                    <h5>No reserved parking spots.</h5>
                    <div id="datetime"></div>
                    <p>Find convenienet & affordable parking <a href="/spots">here!</a></p>
                  </div>

                <% else %>
                  <div class="col s6" id="reserved-spots">
                    <h4 class="user-host-title">Your Reserved <br>Parking Spots</h4>
                    <div class="dash-reservations">
                      <%= render 'reservation_card'%>
                      <!-- #link_to "Pay", new_charge_path(@spot), class: "waves-effect btn #757575 grey darken-1"  -->
                    </div>
                  </div>
                <% end %>



                <!-- Hosted Spots Column -->
                <div class="col s6" id="hosted-spots">
                  <!-- Display hosted locations if user is a host -->
                  <%if current_user.spots.empty? %>
                  <h5>You don't currently host any parking spots.</h5>
                  <p>Hosting is easy. Click <a href="spots/new">here</a> to become a host!</p>
                  <% else %>
                  <h4 class="user-host-title">Your Hosted <br>Parking Spots</h4>
                  <%= render 'hosting_card' %>
                  <% end %>
                </div>
                </div>

              </div>

            </div>

          </div>
          <%= render 'right_sidebar' %>


        </div>
        <script type="text/javascript">
          initialize()
        </script>
      </div>

    </div>

  </div>

      <!-- MOBILE VIEW (No Columns) -->
      <div class="hide-on-med-and-up">

        <div class="container">


        <%= render 'searchbar' %>
        <div id="mapDashMobile"></div>
        <a href="/spots", class="waves-effect btn #ef6c00 orange darken-3", id="become-host-button"><i class="small material-icons">directions_car</i>Park Now</a>
        <a class="waves-effect btn #42a5f5 blue lighten-1 modal-trigger" href="#modal1", id="become-host-button"><i class="small material-icons">add_location</i>Become A Host</a>
        <!-- Reserved Spots Column -->
        <%if current_user.bookings.empty? %>
          <div class="col s6" id="reserved-spots">
            <h5>No reserved parking spots.</h5>
            <div id="datetime"></div>
            <p>Find convenienet & affordable parking <a href="/spots">here!</a></p>
          </div>
        <% else %>
          <div class="col s6" id="reserved-spots">
            <h4 class="user-host-title">Your Reserved <br>Parking Spots</h4>
            <div class="dash-reservations">
              <%= render 'reservation_card'%>
            </div>
          </div>
        <% end %>

        <!-- Display hosted locations if user is a host -->
        <%if current_user.spots.empty? %>
          <h5>You don't currently host any parking spots.</h5>
          <p>Hosting is easy. Click <a href="spots/new">here</a> to become a host!</p>
        <% else %>
          <h4 class="user-host-title">Your Hosted <br>Parking Spots</h4>
          <%= render 'hosting_card' %>
        <% end %>

          <%= render 'right_sidebar' %>
        </div>
        <script type="text/javascript">

          function mobileMap(){
            map3 = document.getElementById('mapDashMobile');
            var myOptions = {
              zoom: 12,
              center: new google.maps.LatLng(25.7617, -80.1918)
            }
            var mapSmall = new google.maps.Map(map3, myOptions);

            for (var i = 0; i < gon.latlng.length; i++) {
              // var latlng = new google.maps.LatLng(gon.latlng[i][0], gon.latlng[i][1])
              var latlng = {lat: gon.latlng[i][0],lng: gon.latlng[i][1]}
              var park = new google.maps.Marker({
                position: latlng,
                map: mapSmall
              });
              console.log(gon.results)
            }
          };

          mobileMap();
        </script>


      </div>

app/views/dashboard/show.html.erb
<h1>Directions to your parking spot</h1>

<div id="showMap" style="height: 500px">

</div>
<%= @spot_ids %>

<script type="text/javascript">
var showLat;
var directions = document.getElementById("Directions")


function initMap() {

  var directionsService = new google.maps.DirectionsService;
  var directionsDisplay = new google.maps.DirectionsRenderer;
    if (navigator.geolocation) {
        navigator.geolocation.getCurrentPosition(showPosition);
    } else {
        x.innerHTML = "Geolocation is not supported by this browser.";
    }

function showPosition(position) {
  showLat = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);

  var options = {
    zoom: 10,
    center: showLat
  }
  var map3 = new google.maps.Map(document.getElementById('showMap'), options)
  // new google.maps.Marker({
  //         map: map3,
  //         position: showLat
  //       })
  //     }
directionsDisplay.setMap(map3);
calculateAndDisplayRoute(directionsService, directionsDisplay);
  }
}
function calculateAndDisplayRoute(directionsService, directionsDisplay) {
  directionsService.route({
    origin: showLat,//document.getElementById('start').value,
    destination: gon.current_street,//document.getElementById('end').value,
    travelMode: 'DRIVING'
  }, function(response, status) {
    if (status === 'OK') {
      directionsDisplay.setDirections(response);
    } else {
      window.alert('Directions request failed due to ' + status);
    }
  });
}
//    49 sw 11th st
// function initMap() {
//   getLocation();
//   var userLatLng = new google.maps.LatLng(position.coords.latitude, position.coords.longitude);
//    var directionsService = new google.maps.DirectionsService;
//    var directionsDisplay = new google.maps.DirectionsRenderer;
//    var map3 = new google.maps.Map(document.getElementById('showMap'), {
//      zoom: 7,
//      center: showLat
//    });
  // directionsDisplay.setMap(map3);

   //calculateAndDisplayRoute(directionsService, directionsDisplay);

 // }

 // function calculateAndDisplayRoute(directionsService, directionsDisplay) {
 //   directionsService.route({
 //     origin: gon.start_address,//document.getElementById('start').value,
 //     destination: gon.end_address,//document.getElementById('end').value,
 //     travelMode: 'DRIVING'
 //   }, function(response, status) {
 //     if (status === 'OK') {
 //       directionsDisplay.setDirections(response);
 //     } else {
 //       window.alert('Directions request failed due to ' + status);
 //     }
 //   });
 // }


initMap();
</script>